server:
  port: 8191
  servlet:
    context-path: /schedule-service #/three-oceans.fitness

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/scheduledb
    username: postgres
    password: 123
  jpa:
    database: POSTGRESQL
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect


integration:
  account-service:
    url: http://localhost:8189/account-service
    read-timeout: 10000
    write-timeout: 5000
    connect-timeout: 500


strings:
  daysOfAWeek: Понедельник, Вторник, Среда, Четверг, Пятница, Суббота, Воскресенье
  schedule: 8:00, 9:30, 11:00, 12:30, 16:00, 17:30, 19:00, 20:30
